# Generated by Django 5.1.5 on 2025-04-27 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100, null=True)),
                ('seats', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('M', 'Manual'), ('A', 'Auto'), ('H', 'Hybrid')], default='M', max_length=1)),
                ('price_per_day', models.PositiveSmallIntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('licence_plate_no', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='car')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('car_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('total_price', models.PositiveSmallIntegerField(default=0)),
                ('address', models.TextField()),
                ('cnic', models.CharField(max_length=15)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('C', 'Cancelled'), ('S', 'PAID')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='booking.car')),
            ],
        ),
    ]
