# Generated by Django 5.1.5 on 2025-05-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
